/**
 * AI Video Blocker — Storage Utilities
 * Quản lý settings và cache qua chrome.storage.local
 */

const StorageManager = {
  /** Default settings cho extension */
  DEFAULT_SETTINGS: {
    enabled: true,
    sensitivity: 'medium', // 'low' | 'medium' | 'high'
    detectionProfile: 'recall-first', // 'balanced' | 'recall-first'
    detectorVersion: 7,
    parentalPassword: '',
    isLocked: false,
    whitelistedChannels: [],
    blacklistedChannels: [],
    stats: {
      totalBlocked: 0,
      totalScanned: 0,
      lastActive: null,
      byContext: {
        home: { scanned: 0, blocked: 0 },
        search: { scanned: 0, blocked: 0 },
        watch: { scanned: 0, blocked: 0 },
        shorts: { scanned: 0, blocked: 0 },
        channel: { scanned: 0, blocked: 0 },
        other: { scanned: 0, blocked: 0 }
      },
      byMethod: {
        label: 0,
        keyword: 0,
        pattern: 0,
        channel: 0,
        combination: 0,
        disclosure: 0,
        childRisk: 0,
        gemini: 0,
        openrouter: 0,
        none: 0
      },
      bySignal: {
        strong: 0,
        medium: 0,
        weak: 0
      },
      byRiskLevel: {
        safe: 0,
        caution: 0,
        block: 0
      },
      byRiskCategory: {
        sexual: 0,
        violence: 0,
        horror: 0,
        self_harm: 0,
        dangerous_acts: 0,
        drugs: 0,
        profanity: 0,
        disturbing_kids_content: 0
      }
    },
    activeProvider: 'gemini',
    gemini: {
      enabled: false,
      hasApiKey: false,
      model: 'gemini-3.1-flash-lite-preview',
      includeThumbnail: false,
      timeoutMs: 3500,
      thumbnailTimeoutMs: 6000,
      maxCaptionChars: 4000,
      promptVersion: 1
    },
    openrouter: {
      enabled: false,
      hasApiKey: false,
      model: 'openrouter/free',
      autoFallback: true,
      fallbackModels: [
        'google/gemma-4-31b-it:free',
        'qwen/qwen3-coder:free',
        'openai/gpt-oss-20b:free',
        'nvidia/nemotron-nano-9b-v2:free'
      ],
      timeoutMs: 5000
    },
    // Backward-compatible synthetic/AI keyword database.
    aiKeywords: {
      high: [
        'ai generated', 'ai-generated', 'made with ai', 'created by ai',
        'generated by ai', 'ai generated content', '100% ai', 'fully ai',
        'tạo bởi ai', 'tạo bằng ai', 'video ai', 'ai tạo', 'nội dung ai'
      ],
      medium: [
        'ai art', 'ai animation', 'ai video', 'ai movie',
        'ai story', 'ai stories', 'videos ai', 'video ai',
        'deepfake', 'synthetic media', 'neural rendering',
        'text to video', 'image to video', 'ai music video',
        'ai cartoon', 'ai hoạt hình', 'ai phim',
        'sora ai', 'kling ai', 'runway gen', 'pika labs', 'haiper',
        'luma dream machine', 'minimax video', 'vidu ai',
        'veo 3', 'google veo', 'hailuo ai', 'seedance',
        'synthesia', 'heygen', 'd-id', 'colossyan',
        'higgsfield ai', 'runway gen-3', 'kling 2', 'wan 2.1', 'wan 2.2',
        '#aiart', '#aivideo', '#aigeneratedcontent', '#aislop'
      ],
      low: [
        'artificial intelligence', 'machine learning', 'neural network',
        'generated', 'synthetic', 'automated', 'bot-created',
        'sora', 'kling', 'runway', 'pika', 'veo',
        'trí tuệ nhân tạo', 'học máy', '#ai'
      ]
    },
    syntheticKeywords: null,
    // AI tool patterns in titles/descriptions
    aiToolPatterns: [
      /made\s*(with|using|by)\s*(sora|kling|runway|pika|luma|minimax|heygen|synthesia|d-id)/i,
      /\b(sora|kling|runway|pika)\s*(ai|video|gen)/i,
      /(ai|artificial.?intelligence)\s*(generated|created|made|produced)/i,
      /tạo\s*(bằng|bởi|từ)\s*(ai|trí tuệ nhân tạo)/i,
      /#(aigenerated|aiart|aivideo|aislop|aicontent)/i,
      /\b(kling|sora|veo|runway)\s*(1(\.5)?|2|3)?\s*(ai|video|gen|model)\b/i,
      /\b(google\s*veo|veo\s*3|hailuo\s*ai|seedance|higgsfield\s*ai|wan\s*2(\.\d)?)\b/i,
      /\b(prompt\s*to\s*video|text\s*to\s*video|image\s*to\s*video)\b/i,
      /\b(videos?|shorts?|stories|story|cartoons?|animation|movie|film)\s*ai\b/i,
      /\bai\s*(videos?|shorts?|stories|story|cartoons?|animation|movie|film)\b/i,
      /\b(100%\s*ai|fully\s*ai|ai\s*only)\b/i
    ],
    childRiskKeywords: {
      sexual: {
        high: ['sex', 'porn', 'porno', 'nude', 'nudity', 'xxx', '18+', 'onlyfans', 'khiêu dâm', 'khỏa thân', 'loạn luân'],
        medium: ['sexy', 'gợi cảm', 'nhạy cảm', 'hở hang', 'adult content', 'sexual', 'seduce', 'provocative'],
        low: ['kiss prank', 'crush', 'body reveal']
      },
      violence: {
        high: ['murder', 'kill', 'killing', 'blood', 'gore', 'decapitation', 'suicide scene', 'giết', 'giết người', 'máu me', 'chặt đầu', 'tra tấn'],
        medium: ['violence', 'violent', 'fight', 'fighting', 'weapon', 'knife', 'gun', 'shooting', 'đánh nhau', 'bạo lực', 'dao', 'súng', 'bắn nhau'],
        low: ['battle', 'war', 'đại chiến', 'trận chiến']
      },
      horror: {
        high: ['horror', 'scary', 'creepy', 'nightmare', 'jumpscare', 'ma quỷ', 'kinh dị', 'ác quỷ', 'quái vật đáng sợ'],
        medium: ['ghost', 'monster', 'haunted', 'zombie', 'ma', 'quái vật', 'rùng rợn', 'ám ảnh'],
        low: ['dark story', 'bí ẩn', 'hù dọa']
      },
      self_harm: {
        high: ['self harm', 'self-harm', 'suicide', 'kill myself', 'cutting', 'tự tử', 'tự hại', 'rạch tay'],
        medium: ['depression challenge', 'suicide story', 'muốn chết', 'trầm cảm tự hại'],
        low: ['sad ending', 'đau khổ']
      },
      dangerous_acts: {
        high: ['dangerous challenge', 'choking challenge', 'fire challenge', 'tide pod', 'prank gone wrong', 'thử thách nguy hiểm', 'trò nguy hiểm'],
        medium: ['stunt', 'dare', 'prank', 'illegal activity', 'đua xe', 'nhảy lầu', 'nghịch lửa', 'thử thách'],
        low: ['challenge', 'dám làm']
      },
      drugs: {
        high: ['drug use', 'cocaine', 'heroin', 'meth', 'ma túy', 'cần sa', 'thuốc lắc'],
        medium: ['drugs', 'weed', 'vape', 'alcohol', 'say rượu', 'rượu bia', 'hút thuốc'],
        low: ['party hard']
      },
      profanity: {
        high: ['fuck', 'bitch', 'shit', 'địt', 'đụ', 'lồn', 'cặc'],
        medium: ['damn', 'asshole', 'chửi tục', 'tục tĩu', 'mất dạy'],
        low: ['wtf']
      },
      disturbing_kids_content: {
        high: ['elsagate', 'pregnant elsa', 'spiderman pregnant', 'cartoon blood', 'kidnapping cartoon', 'bắt cóc trẻ em', 'hoạt hình máu me'],
        medium: ['kids horror', 'children horror', 'baby monster', 'cartoon violence', 'nhân vật trẻ em kinh dị', 'hoạt hình kinh dị'],
        low: ['weird kids cartoon', 'strange cartoon']
      }
    },
    childRiskPatterns: [
      /\b(kids?|children|baby|cartoon|elsa|spiderman|minecraft|roblox|among\s*us)\b.{0,80}\b(horror|blood|gore|pregnant|kiss|kill|murder|monster|scary)\b/i,
      /\b(horror|blood|gore|pregnant|kiss|kill|murder|monster|scary)\b.{0,80}\b(kids?|children|baby|cartoon|elsa|spiderman|minecraft|roblox|among\s*us)\b/i,
      /(trẻ em|em bé|thiếu nhi|hoạt hình|siêu nhân|công chúa).{0,80}(kinh dị|máu|giết|bắt cóc|mang thai|hôn|quái vật)/i,
      /(kinh dị|máu|giết|bắt cóc|mang thai|hôn|quái vật).{0,80}(trẻ em|em bé|thiếu nhi|hoạt hình|siêu nhân|công chúa)/i
    ],
    captionScan: {
      enabled: true,
      maxChars: 5000,
      timeoutMs: 2000,
      preferredLanguages: ['vi', 'en']
    }
  },

  /**
   * Lấy settings hiện tại, merge với defaults
   */
  async getSettings() {
    try {
      const data = await chrome.storage.local.get('settings');
      const storedSettings = data.settings || {};
      const storedVersion = Number(storedSettings.detectorVersion || 0);
      const settings = { ...this.DEFAULT_SETTINGS, ...storedSettings };
      delete settings.blockMode;
      settings.aiToolPatterns = this.DEFAULT_SETTINGS.aiToolPatterns;
      settings.childRiskPatterns = this.DEFAULT_SETTINGS.childRiskPatterns;
      settings.captionScan = { ...this.DEFAULT_SETTINGS.captionScan, ...(storedSettings.captionScan || {}) };
      settings.gemini = this._sanitizeGeminiSettings(storedSettings.gemini);
      settings.openrouter = this._sanitizeOpenRouterSettings(storedSettings.openrouter);
      if (!settings.activeProvider) settings.activeProvider = this.DEFAULT_SETTINGS.activeProvider;
      settings.stats = this._mergeStats(storedSettings.stats);
      if (storedVersion < this.DEFAULT_SETTINGS.detectorVersion) {
        settings.detectorVersion = this.DEFAULT_SETTINGS.detectorVersion;
        settings.aiKeywords = this.DEFAULT_SETTINGS.aiKeywords;
        settings.syntheticKeywords = this.DEFAULT_SETTINGS.aiKeywords;
        settings.childRiskKeywords = this.DEFAULT_SETTINGS.childRiskKeywords;
      }
      if (!settings.syntheticKeywords) settings.syntheticKeywords = settings.aiKeywords || this.DEFAULT_SETTINGS.aiKeywords;
      if (!settings.childRiskKeywords) settings.childRiskKeywords = this.DEFAULT_SETTINGS.childRiskKeywords;
      return settings;
    } catch (e) {
      console.warn('[AIBlocker] Storage read error:', e);
      return {
        ...this.DEFAULT_SETTINGS,
        syntheticKeywords: this.DEFAULT_SETTINGS.aiKeywords,
        gemini: this._sanitizeGeminiSettings(),
        stats: this._mergeStats()
      };
    }
  },

  /**
   * Cập nhật settings
   */
  async updateSettings(partial) {
    const current = await this.getSettings();
    const cleanedPartial = this._sanitizeSettingsPartial(partial);
    const updated = { ...current, ...cleanedPartial };
    if (cleanedPartial.gemini) {
      updated.gemini = this._sanitizeGeminiSettings({
        ...current.gemini,
        ...cleanedPartial.gemini
      });
    }
    if (cleanedPartial.openrouter) {
      updated.openrouter = this._sanitizeOpenRouterSettings({
        ...current.openrouter,
        ...cleanedPartial.openrouter
      });
    }
    const persistableSettings = { ...updated };
    delete persistableSettings.aiToolPatterns;
    delete persistableSettings.childRiskPatterns;
    delete persistableSettings.blockMode;
    persistableSettings.gemini = this._sanitizeGeminiSettings(persistableSettings.gemini);
    persistableSettings.openrouter = this._sanitizeOpenRouterSettings(persistableSettings.openrouter);
    await chrome.storage.local.set({ settings: persistableSettings });
    return updated;
  },

  /**
   * Lấy cache video đã scan
   */
  async getVideoCache() {
    try {
      const data = await chrome.storage.local.get('videoCache');
      return data.videoCache || {};
    } catch (e) {
      return {};
    }
  },

  /**
   * Cache kết quả scan video
   * @param {string} videoId
   * @param {object} result - { isAI, confidence, method, timestamp }
   */
  async cacheVideoResult(videoId, result) {
    const cache = await this.getVideoCache();
    cache[videoId] = {
      ...result,
      timestamp: Date.now()
    };

    // Giới hạn cache 5000 entries
    const entries = Object.entries(cache);
    if (entries.length > 5000) {
      const sorted = entries.sort((a, b) => a[1].timestamp - b[1].timestamp);
      const trimmed = Object.fromEntries(sorted.slice(-4000));
      await chrome.storage.local.set({ videoCache: trimmed });
    } else {
      await chrome.storage.local.set({ videoCache: cache });
    }
  },

  async getCaptionCache() {
    try {
      const data = await chrome.storage.local.get('captionCache');
      return data.captionCache || {};
    } catch (e) {
      return {};
    }
  },

  async getCaptionCacheEntry(key) {
    const cache = await this.getCaptionCache();
    return cache[key] || null;
  },

  async cacheCaptionText(key, result) {
    if (!key) return;

    const cache = await this.getCaptionCache();
    cache[key] = {
      ...result,
      timestamp: Date.now()
    };

    const entries = Object.entries(cache);
    if (entries.length > 1000) {
      const sorted = entries.sort((a, b) => a[1].timestamp - b[1].timestamp);
      await chrome.storage.local.set({ captionCache: Object.fromEntries(sorted.slice(-800)) });
    } else {
      await chrome.storage.local.set({ captionCache: cache });
    }
  },

  async getGeminiCache() {
    try {
      const data = await chrome.storage.local.get('geminiCache');
      return data.geminiCache || {};
    } catch (e) {
      return {};
    }
  },

  async getGeminiCacheEntry(key) {
    if (!key) return null;
    const cache = await this.getGeminiCache();
    return cache[key] || null;
  },

  async getGeminiCacheEntries(keys = []) {
    const cache = await this.getGeminiCache();
    const result = {};
    for (const key of keys) {
      if (cache[key]) result[key] = cache[key];
    }
    return result;
  },

  async cacheGeminiResult(key, result) {
    if (!key) return;

    const cache = await this.getGeminiCache();
    cache[key] = {
      ...result,
      timestamp: Date.now()
    };

    const entries = Object.entries(cache);
    if (entries.length > 3000) {
      const sorted = entries.sort((a, b) => (a[1].timestamp || 0) - (b[1].timestamp || 0));
      await chrome.storage.local.set({ geminiCache: Object.fromEntries(sorted.slice(-2400)) });
    } else {
      await chrome.storage.local.set({ geminiCache: cache });
    }
  },

  async clearGeminiCache() {
    await chrome.storage.local.set({ geminiCache: {} });
    return { ok: true };
  },

  /**
   * Tăng counter thống kê
   */
  async incrementStat(key) {
    const settings = await this.getSettings();
    settings.stats[key] = (settings.stats[key] || 0) + 1;
    settings.stats.lastActive = Date.now();
    await this.updateSettings({ stats: settings.stats });
  },

  /**
   * Cập nhật thống kê theo batch để tránh ghi storage quá nhiều.
   * @param {object} payload
   */
  async updateDetectionStats(payload = {}) {
    const settings = await this.getSettings();
    const stats = settings.stats || {};
    const context = payload.context || 'other';
    const method = payload.method || 'none';
    const signalCounts = payload.signalCounts || {};

    stats.totalScanned = (stats.totalScanned || 0) + (payload.scanned || 0);
    stats.totalBlocked = (stats.totalBlocked || 0) + (payload.blocked || 0);
    stats.lastActive = Date.now();

    if (!stats.byContext) stats.byContext = {};
    if (!stats.byContext[context]) stats.byContext[context] = { scanned: 0, blocked: 0 };
    stats.byContext[context].scanned += payload.scanned || 0;
    stats.byContext[context].blocked += payload.blocked || 0;

    if (!stats.byMethod) stats.byMethod = {};
    stats.byMethod[method] = (stats.byMethod[method] || 0) + (payload.blocked || 0);

    if (!stats.bySignal) stats.bySignal = {};
    for (const level of ['strong', 'medium', 'weak']) {
      const value = Number(signalCounts[level] || 0);
      stats.bySignal[level] = (stats.bySignal[level] || 0) + value;
    }

    if (!stats.byRiskLevel) stats.byRiskLevel = {};
    const riskLevel = payload.riskLevel || 'safe';
    stats.byRiskLevel[riskLevel] = (stats.byRiskLevel[riskLevel] || 0) + (payload.scanned || 0);

    if (!stats.byRiskCategory) stats.byRiskCategory = {};
    for (const category of payload.riskCategories || []) {
      stats.byRiskCategory[category] = (stats.byRiskCategory[category] || 0) + (payload.blocked || 0);
    }

    await this.updateSettings({ stats });
    return stats;
  },

  /**
   * Kiểm tra password phụ huynh
   */
  async verifyPassword(input) {
    const settings = await this.getSettings();
    if (!settings.parentalPassword) return true;
    return input === settings.parentalPassword;
  },

  /**
   * Xác định context trang YouTube hiện tại.
   */
  getYouTubeContext(pathname = '') {
    if (pathname === '/watch') return 'watch';
    if (pathname.startsWith('/results')) return 'search';
    if (pathname.startsWith('/shorts')) return 'shorts';
    if (pathname.startsWith('/@') || pathname.startsWith('/channel/') || pathname.startsWith('/c/')) return 'channel';
    if (pathname === '/' || pathname.startsWith('/feed/')) return 'home';
    return 'other';
  },

  /**
   * Kiểm tra channel có trong whitelist
   */
  async isWhitelisted(channelId) {
    const settings = await this.getSettings();
    return settings.whitelistedChannels.includes(channelId);
  },

  _mergeStats(storedStats = {}) {
    const defaults = this.DEFAULT_SETTINGS.stats;
    return {
      ...defaults,
      ...storedStats,
      byContext: { ...defaults.byContext, ...(storedStats.byContext || {}) },
      byMethod: { ...defaults.byMethod, ...(storedStats.byMethod || {}) },
      bySignal: { ...defaults.bySignal, ...(storedStats.bySignal || {}) },
      byRiskLevel: { ...defaults.byRiskLevel, ...(storedStats.byRiskLevel || {}) },
      byRiskCategory: { ...defaults.byRiskCategory, ...(storedStats.byRiskCategory || {}) }
    };
  },

  _sanitizeSettingsPartial(partial = {}) {
    const sanitized = { ...(partial || {}) };
    if (sanitized.gemini) {
      sanitized.gemini = this._sanitizeGeminiSettings(sanitized.gemini);
    }
    if (sanitized.openrouter) {
      sanitized.openrouter = this._sanitizeOpenRouterSettings(sanitized.openrouter);
    }
    return sanitized;
  },

  _sanitizeGeminiSettings(gemini = {}) {
    const source = { ...(gemini || {}) };
    const hasApiKey = Boolean(source.hasApiKey || source.apiKey);
    delete source.apiKey;
    return {
      ...this.DEFAULT_SETTINGS.gemini,
      ...source,
      hasApiKey
    };
  },

  _sanitizeOpenRouterSettings(openrouter = {}) {
    const source = { ...(openrouter || {}) };
    const hasApiKey = Boolean(source.hasApiKey || source.apiKey);
    delete source.apiKey;
    return {
      ...this.DEFAULT_SETTINGS.openrouter,
      ...source,
      hasApiKey
    };
  }
};

// Export cho cả content script và service worker
if (typeof globalThis !== 'undefined') {
  globalThis.StorageManager = StorageManager;
}
